env:
    browser: true
    es2021: true
    jest/globals: true
extends:
    - 'plugin:react/recommended'
    - airbnb
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:testing-library/react
    - plugin:jest/recommended
    - prettier
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
    - testing-library
    - jest
settings:
    import/resolver:
        node:
            moduleDirectory:
                - node_modules
                - src/
            paths:
                - src
            extensions:
                - '.js'
                - '.jsx'
                - '.ts'
                - '.tsx'
    jest:
        version: 26
rules:
    testing-library/await-async-query: error
    testing-library/no-await-sync-query: error
    testing-library/no-debug: warn
    react/jsx-uses-react: 'off'
    react/react-in-jsx-scope: 'off'
    import/extensions:
        - error
        - ignorePackages
        - js: never
          jsx: never
          ts: never
          tsx: never
    react/jsx-filename-extension:
        - 1
        - extensions:
              - '.js'
              - '.jsx'
              - '.ts'
              - '.tsx'
    jest/no-disabled-tests: warn
    jest/no-focused-tests: error
    jest/no-identical-title: error
    jest/prefer-to-have-length: warn
    jest/valid-expect: error
    no-use-before-define: 'off'
    'no-undef': off
    indent:
        - error
        - 4
        - SwitchCase: 1
    import/prefer-default-export: 'off'
    no-param-reassign:
        - error
        - props: false
    no-unused-vars: 'off'
    '@typescript-eslint/no-unused-vars':
        - warn
    '@typescript-eslint/ban-types':
        - error
        - extendDefaults: true
          types:
              '{}': false
    '@typescript-eslint/no-empty-function': off
    '@typescript-eslint/triple-slash-reference': 'off'
    '@typescript-eslint/explicit-module-boundary-types': 'off'
