env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - plugin:testing-library/react
  - plugin:jest/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - testing-library
  - jest
settings:
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".jsx"
      - ".ts"
      - ".tsx"
rules:
  testing-library/await-async-query: error
  testing-library/no-await-sync-query: error
  testing-library/no-debug: warn
  react/jsx-uses-react: 'off'
  react/react-in-jsx-scope: 'off'
  import/extensions:
  - error
  - ignorePackages
  - js: never
    jsx: never
    ts: never
    tsx: never
  react/jsx-filename-extension:
  - 1
  - extensions:
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
  no-use-before-define: 'off'
  "@typescript-eslint/no-use-before-define":
  - error
  indent:
  - error
  - 4




